spring:
  application:
    name: medistock-api

server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
    include-message: never

medistock:
  persistencia: ${PERSISTENCIA:firestore}

  firebase:
    credenciais: ${FIREBASE_CREDENTIALS:serviceAccount.json}

  jwt:
    secret: ${JWT_SECRET:desenvolvimento-medistock-chave-local-nao-use-em-producao}
    expiracao-ms: ${JWT_EXPIRATION:86400000}

  cors:
    origens: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8100,http://localhost:3000}

  dominios-institucionais: fiap.com.br,hc.unicamp.br,hc.usp.br,einstein.br,hospital.gov.br,saude.sp.gov.br
